### PR TITLE
south-on-top option

### PR DESCRIPTION
**Pull request by matijaskala**

### CODE REVIEW

**Comment by Eignar17** [comment]
is disable and active funcion is implement not complete

**Comment by Eignar17** [comment]
compile new option and test result of bugs or stable

**Comment by matijaskala** [comment]
It's stable in the sense that it won't crash. But it could be drawn incorrectly.

**Comment by Eignar17** [comment]
ok test your new option find to bugs

**Comment by Eignar17** [comment]
is new option not works

**Comment by Eignar17** [comment]
is code is complete not bugs

**Comment by soreau** [comment]
Why would you want south on top?

**Comment by ethus3h** [comment]
@soreau, either as an educational technique to visually draw attention to the large quantity of water that comprises the Earth, or because one lives in the southern hemisphere and wants home on top :3

**Pull request merged**
